## 01.텐서 초괴화
- 초기화:텐서에서 특정 값을 채워서 생성하는 것


In [3]:
import torch
import numpy as np

torch.__version__

'2.5.1'

### 1-1.초기화 되지 않은 tenosr
- 특정 값이 채워지지 않은 사태로 생성하는 것

In [12]:
tensor = torch.empty(4,2)
print(tensor)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### 1-2 상수로 초기화된 tenosr
- 'torch.zeros()'
- 'torch.ones'

In [14]:
a = torch.ones(3,4,dtype=torch.long)#dtype = 데이터 타입 지정
b = torch.zeros(2,2)
print(a)
print(b)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([[0., 0.],
        [0., 0.]])


### 1-3. 무작위로 초괴화된 tenosr
- torch.rand: 0~1 사이값으로 무작위 초괴화
- torcg.randn: 표준정규분포에서 무작위로 초괴화

In [15]:
a = torch.rand(3,3)
b = torch.randn(3,3)
print(a,b)

tensor([[0.4315, 0.2008, 0.0075],
        [0.6045, 0.9040, 0.0157],
        [0.2349, 0.8798, 0.6349]]) tensor([[-1.5358,  1.6082, -1.1976],
        [ 0.8418,  0.1596, -1.2320],
        [-0.4709, -0.9995, -0.8262]])


### 1-4 직접 입력한 값으로 초기화

In [16]:
a = torch.tensor([1,2.3])
a

tensor([1.0000, 2.3000])

### 1-5 Numpy 배열로부터 초괴화

In [26]:
nd_arr = np.array([1,2,3])
a = torch.from_numpy(nd_arr)

b = torch.tensor([1,2.3])
new_nd = b.numpy()
type(new_nd)

numpy.ndarray

### 1-6 특정 텐서와 같은 타입, 무작위로 값을 채움

In [22]:
a = torch.ones(3,4,dtype=torch.long)
b =torch.randn_like(a,dtype=torch.float)
b

tensor([[-2.6619,  1.0947,  0.2391,  0.0781],
        [ 0.4917,  0.7260,  0.3619,  1.0362],
        [ 0.0083, -1.5964, -0.2925, -0.5400]])

## 1-7 텐서의 속성

In [29]:
tensor = torch.empty(3,4)
print(tensor.size()) #사이즈
print(tensor.shape) #사이즈
print(tensor.dtype) #데이터 타입
print(tensor.device)

torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu


### 1-8. 특정 타입의 텐서 생성

In [33]:
tensor = torch.rand(3,4,dtype=torch.float64)
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor)
print(float_tensor.dtype)

int_tensor = torch.IntTensor([1.1,2.3,3.4])
print(int_tensor)
print(int_tensor.dtype)

tensor.dtype


tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3], dtype=torch.int32)
torch.int32


torch.float64

### 1-9. 데이터 타입 캐스팅

In [34]:
float_tensor = torch.FloatTensor([1,2,3])
print(float_tensor.int())
int_tensor = torch.IntTensor([1,2,3])
print(int_tensor.float())


tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.])


### 1-10 CUDA Tensor

In [37]:
tensor = torch.rand(3,4,dtype=torch.float64)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor = tensor.to(device)
tensor.device


device(type='cpu')

### 1-11. 다차원 텐서 표현

1-11-1. 0D Tensor(Scalar)
- 하나의 값을 담고 있는 텐서

In [41]:
t0 = torch.tensor(100)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(100)


#### 1-11-2 1D Tensor(vector)
- 값들을 저장하고 있는 리스트와 유사한 텐서

In [42]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


#### 1-11-3 2D Tensor(metrix)
- 행렬과 같은 모양으로 두개의 축이 존재

In [43]:
t2 = torch.tensor([[1,2,3],[1,2,3]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [1, 2, 3]])


#### 1-11-4 3D Tensor(Cude)
- 큐브와 같은 현태로 세개의 축이 존재

In [47]:
t3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

SyntaxError: invalid syntax (454959162.py, line 2)

#### 1-11-5 4D Tensor(Cude)

In [50]:
t4 = torch.rand(2,3,4,5)
print(t4.ndim)
print(t4.shape)
print(t4)

4
torch.Size([2, 3, 4, 5])
tensor([[[[0.5549, 0.4595, 0.9804, 0.3715, 0.4011],
          [0.9136, 0.2797, 0.5277, 0.3918, 0.6454],
          [0.9028, 0.3532, 0.6024, 0.5634, 0.0565],
          [0.7736, 0.2720, 0.0544, 0.1757, 0.6139]],

         [[0.5409, 0.2736, 0.9822, 0.8134, 0.4178],
          [0.2876, 0.2981, 0.6449, 0.9155, 0.1861],
          [0.6819, 0.2004, 0.3585, 0.6177, 0.6519],
          [0.6811, 0.2692, 0.0044, 0.1648, 0.6435]],

         [[0.5956, 0.4565, 0.5794, 0.7166, 0.9540],
          [0.2094, 0.7941, 0.4897, 0.8409, 0.9112],
          [0.7881, 0.2693, 0.4573, 0.2550, 0.1263],
          [0.8984, 0.6322, 0.7776, 0.4465, 0.8664]]],


        [[[0.2500, 0.6683, 0.0273, 0.0805, 0.6417],
          [0.7182, 0.9771, 0.5369, 0.3047, 0.1094],
          [0.4723, 0.0437, 0.9979, 0.3269, 0.3519],
          [0.7928, 0.4740, 0.3651, 0.3695, 0.0748]],

         [[0.2314, 0.8313, 0.2493, 0.8462, 0.3952],
          [0.9088, 0.9411, 0.2869, 0.9771, 0.6164],
          [0.2722, 0.9815, 