## 02. 텐서의 연산

In [1]:
import torch

### 2-1. 산술연산

In [6]:
tensor = torch.rand(2,2)
print(tensor)

tensor = tensor + 1
print(tensor)

tensor = tensor * 2
print(tensor)

tensor([[0.0636, 0.0464],
        [0.0568, 0.4883]])
tensor([[1.0636, 1.0464],
        [1.0568, 1.4883]])
tensor([[2.1272, 2.0927],
        [2.1136, 2.9765]])


In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)
#더하기
add = torch.add(x,y)
print(x,y)
print(add)
print(x+y)

# in_place 바꿔치기 연산
add =torch.add(x,y)
print(add)
y.add_(x)
print(y)

tensor([[0.7039, 0.7527],
        [0.7633, 0.4537]]) tensor([[0.3812, 0.5877],
        [0.2888, 0.0544]])
tensor([[1.0851, 1.3404],
        [1.0522, 0.5081]])
tensor([[1.0851, 1.3404],
        [1.0522, 0.5081]])
tensor([[1.0851, 1.3404],
        [1.0522, 0.5081]])
tensor([[1.0851, 1.3404],
        [1.0522, 0.5081]])


In [14]:
# 빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
sub = torch.sub(x,y)
print(x-y)
print(sub)

tensor([[-0.6477, -0.5657],
        [-0.4141, -0.7675]])
tensor([[-0.6477, -0.5657],
        [-0.4141, -0.7675]])


In [15]:
#곱하기
# 빼기
x = torch.rand(2,2)
y = torch.rand(2,2)
mul = torch.mul(x,y)
print(x*y)
print(mul)

tensor([[0.7626, 0.1801],
        [0.0643, 0.2340]])
tensor([[0.7626, 0.1801],
        [0.0643, 0.2340]])


In [17]:
#나누기
x = torch.rand(2,2)
y = torch.rand(2,2)
div= torch.div(x,y)
print(x/y)
print(div)

tensor([[ 1.6007,  0.2933],
        [14.6987,  0.9169]])
tensor([[ 1.6007,  0.2933],
        [14.6987,  0.9169]])
